### ISSUE TITLE
Best practise to change the font

### ISSUE THREAD

**Issue by kpilard** [marcosmoura/vue-material#199]
We want to change the font from Roboto to Notto Sans. 

Is there a suggested way?

**Comment by marcosmoura** [comment]
Hi @kpilard 

Just insert the [Noto Sans](https://fonts.google.com/specimen/Noto+Sans?selection.family=Noto+Sans:400,700) font and set it in your css:
``` scss
body: {
  font-family: 'Noto Sans', Roboto, sans-serif;
}
```

Thanks!
