### ISSUE TITLE
enable aligning the head/cell content in table to center

### ISSUE THREAD

**Issue by huhk-sysu** [marcosmoura/vue-material#208]
I wonder why there's left-alignment and right-alignment but no center-alignment.
I think center-alignment may look more beautiful.
How about using a property like `md-table-align = "left/center/right" ?

So far`my workaround is:
``` css
.md-table .md-table-cell.md-has-action .md-table-cell-container {
  justify-content: space-around;
}
.md-table .md-table-head {
  text-align: center;
}
.md-table .md-table-cell {
  text-align: center;
}
```
here's an example
![qq 20161215195823](https://cloud.githubusercontent.com/assets/14769033/21223188/da380e92-c300-11e6-8072-f241c63f1944.png)
