### ISSUE TITLE
Center Toolbar Content

### ISSUE THREAD

**Issue by Caoimhin89** [marcosmoura/vue-material#247]
How would one center buttons, text, or other elements within an md-toolbar element?

**Comment by marcosmoura** [comment]
Just add a class to md-toolbar, like main-toolbar, and add the following css:
``` scss
.main-toolbar {
  justify-content: center;
} 
```

Thank you.
