### ISSUE TITLE
Sizes (md-input-container)

### ISSUE THREAD

**Issue by juppdes** [marcosmoura/vue-material#37]
@marcosmoura  I'm not managing to scale the size of the input fields and others. How do I do ?

**Comment by marcosmoura** [comment]
@juppdes I didn't get it. What do you need? To scale it horizontally to get a full size? Or do you want to increase the size of the font and based on that the container and the input itself would grow?

Like that? ![Text Field](https://material-design.storage.googleapis.com/publish/material_v_9/0Bzhp5Z4wHba3UHZpZjVsYjRHcXc/components_textfields_labels1.png)

**Comment by juppdes** [comment]
Yes, horizontally resize the input size. Like size of 'Price', 'Location'.

**Comment by marcosmoura** [comment]
Well. Right now, as you can see on #35, Vue Material doesn't have a Grid System implemented. Yet. You will need to do it by hand or plug in a grid system library. I would recommend those two (for now):
http://kenwheeler.github.io/structure/
http://flexboxgrid.com/

If you want to implement something by hand you can use this approach:
``` css
.row {
  margin: 0 -8px;
  display: flex;
  flex-flow: row wrap;
}

.column {
  padding: 0 8px;
  flex: 1 0 auto;
}

.column-20 {
  min-width: 20%;
  flex: 1 0 20%;
}

.column-25 {
  min-width: 25%;
  flex: 1 0 25%;
}

.column-33 {
  min-width: 33%;
  flex: 1 0 33%;
}

.column-50 {
  min-width: 50%;
  flex: 1 0 50%;
}

.column-66 {
  min-width: 66%;
  flex: 1 0 66%;
}

.column-75 {
  min-width: 75%;
  flex: 1 0 75%;
}

.column-100 {
  min-width: 100%;
  flex: 1 0 100%;
}
```

``` html
<div class="row">
  <div class="column column-33">
    
  </div>

  <div class="column column-66">
    
  </div>
</div>
```

You can vary the size changing for one of the given sizes on the css part.
If this do not work for you let me know and I will give another temporary solution while grid system is under construction.

Thank you and sorry for only giving to you the temporary solution now.
