### ISSUE TITLE
Stop scrolling `body` while ...

### ISSUE THREAD

**Issue by jonataswalker** [marcosmoura/vue-material#373]
... `<md-dialog>` is open. Could be:

```css
body.md-dialog-active {
  overflow: hidden;
}
```
