### ISSUE TITLE
Remove dependence of Google CDN for fonts, icons

### ISSUE THREAD

**Issue by Samuell1** [marcosmoura/vue-material#476]
Hey, if i need offline mode i cant use CDN, its a any way to drop google cdn and use dependencies or include in assets?

**Comment by jonataswalker** [comment]
You download the desired font from Google, go to https://www.fontsquirrel.com/tools/webfont-generator and generate web fonts. Then load a CSS file with something like this:

```CSS
@font-face {
  font-family: 'roboto_condensedbold';
  src: url("font/robotocondensed-bold-webfont.woff2") format("woff2"), url("font/robotocondensed-bold-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal; }

@font-face {
  font-family: 'roboto_condensedregular';
  src: url("font/robotocondensed-regular-webfont.woff2") format("woff2"), url("font/robotocondensed-regular-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal; }

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local("Material Icons"), local("MaterialIcons-Regular"), url("font/MaterialIcons-Regular.woff2") format("woff2"), url("font/MaterialIcons-Regular.woff") format("woff"); }

@font-face {
  font-family: 'robotobold';
  src: url("font/roboto-bold-webfont.woff2") format("woff2"), url("font/roboto-bold-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal; }

@font-face {
  font-family: 'robotoregular';
  src: url("font/roboto-regular-webfont.woff2") format("woff2"), url("font/roboto-regular-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal; }

@font-face {
  font-family: 'robotothin';
  src: url("font/roboto-thin-webfont.woff2") format("woff2"), url("font/roboto-thin-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal; }
```

Attention for `url` path.
